---
title: "Intro to programming 1"
author: | 
  | Henri Vandendriessche
  | henri.vandendriessche@ens.fr
date: "2023-09-19"
fontsize: 8pt
output:
  beamer_presentation:
    theme: "CambridgeUS"
    incremental: true

  slidy_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Context
========================================================
- inscription on the moodle: https://moodle.u-paris.fr/course/view.php?id=43747
- and discord: https://discord.gg/9hKDQmRu


- Why programming ?
  + **Independence**: Empowers young researchers for independent work.
  + **Thinking Skills**: Develops iterative, computational, and problem-solving thinking.
  + **Essential Skill**: Coding is a vital skill in the digital age.


- Why python ?
  + **Accessibility**: Free and open-source, eliminating cost barriers.
  + **Versatility**: A unified language for data analysis, modeling, and more.
  + **Community**: Supported by a large and active user community. 


- Why programming in python for cognitive sciences ?
  + **Comprehensive Toolkit**: Ideal for data science, modeling, and experimental design.
  + **Research Community**: Thriving community with specialized tools for cognitive sciences. (https://www.frontiersin.org/articles/10.3389/fninf.2015.00011/full)



Survival rules for programming
========================================================

- 1 Try by yourself before seeking solutions.

- 2 Internet is your best friend.

- 3 Read the manual.

- 4 There is always a manual.

- 5 Have you read the fucking manual ?

- 6 Not yet ? Then read it.

- 7 Always review error messages carefully.

- 8 Only then, consider asking ChatGPT for help.


Resources 1/2
========================================================

## Books & ebooks

>  - Gérard Swinnen: Apprendre à Programmer avec Python 3 (5e edition) http://inforef.be/swi/python.htm
    
>  - Al Sweigart: How to automate the boring stuff with Python (2e edition) https://automatetheboringstuff.com/
    
>  - Al Sweigart: Invent Your Own Computer Games with Python (4e edition) http://inventwithpython.com/invent4thed/

>  - Allen B. Downey: Think Python http://greenteapress.com/thinkpython2/ 


Resources 2/2
========================================================

## Online course & Mooc
### Openclassrooms
>  - https://openclassrooms.com/fr/courses/7168871-apprenez-les-bases-du-langage-python
    
>  - https://openclassrooms.com/en/courses/6902811-learn-python-basics
  
### Mooc de l'Inria
>  - https://www.my-mooc.com/fr/mooc/python-des-fondamentaux-a-lutilisation-du-langage/

### Udemy
>  - Udemy: Python programming for absolute beginners: https://www.udemy.com/python-programming-for-absolute-beginners/                

### Code Academy
>  - Code Academy: Learn Python module: https://www.codecademy.com/learn/learn- python

### Other
>  - Python 3: des fondamentaux aux concepts avancés du langage: https://lms.fun-mooc.fr/

### Websites
>  - https://pythontutor.com/ (Visualize and step by step code execution)


Terminal cheat sheet
========================================================

- Bash commands to navigate directories

  + Print Working Directory. Print the path of the current directory
  ```{bash, echo = TRUE, eval= FALSE}
  pwd
  ```

  + List all files of the current directory
  ```{bash, echo = TRUE, eval= FALSE}
  ls folder
  ```

  + Moving into folder1 and subfolder2 at once. 
  ```{bash, echo = TRUE, eval= FALSE}
  cd folder1/subfolder2
  ```

  + Moving out of a directory
  ```{bash, echo = TRUE, eval= FALSE}
  cd ..
  ```
  
  + Going back to the root directory
  ```{bash, echo = TRUE, eval= FALSE}
  cd ~
  ```
  
- "Tab" to use the auto-completion

- Many more bash commands to use...


Writing and running a program with python
========================================================

> - Open sublime

> - Write: 
```{python, echo=TRUE}
print("Hello !")
```

> - Save the file as *hello.py*

> - Open a terminal and navigate to the folder where you have saved your program and run the command: <br><span style="color: grey;">`python hello.py`</span>


Variables and data in python I
========================================================

- A variable is a named container for a particular set of bits or type of data (like integer, float, string etc...)

- Declaring variables
```{python, echo=TRUE}
x = 10
print(x)
```


Variables and data in python II
========================================================

 - Naming variables
    + Use alphanumeric characters and underscores (but no numbers or underscores as the first character).
    + Avoid using reserved keywords.
    + Variables can contain digits but must not consist solely of digits and cannot start with a digit.
    + Variables are case-sensitive; uppercase and lowercase letters are distinct. 
    + There is no length limit for variables.
      ```{python, echo=TRUE}
      x = 10
      print(x)
      abc = 2
      print(abc)
      _ = 5
      print(_)
      ```


Variables and data in python III
========================================================
> - Naming variables
>   + Use alphanumeric characters and underscores (but no numbers or underscores as the first character).
>   + Avoid using reserved keywords.
>   + Variables can contain digits but must not consist solely of digits and cannot start with a digit.
>   + Variables are case-sensitive; uppercase and lowercase letters are distinct. 
>   + There is no length limit for variables.
      ```{python, echo=TRUE, error=TRUE}
      1x = 10
      print(x)
      ``` 
      ```{python, echo=TRUE, error=TRUE}
      a bc = 2
      print(abc)
      ``` 
      ```{python, echo=TRUE, error=TRUE}
      t-t = 10
      print(t-t)
      ```

      This doesn't work
      
  

Variables and data in python IV
========================================================
- Different types of variables: Primitive types
    + integers
      ```{python, echo=TRUE, error=TRUE}
      x = 10
      print(type(x))
      ```
    + float
      ```{python, echo=TRUE, error=TRUE}
      y = 5.5
      print(type(y))
      ```
    + string 
      ```{python, echo=TRUE, error=TRUE}
      z = "test"
      print(type(z))
      ```
    + boolean
      ```{python, echo=TRUE, error=TRUE}
      w = True
      print(type(w))
      ```
      
      
Numeric data et operations 1/2
========================================================


> - Differences between integers and floats


> - Arithmetic operators + - * / %


> - Exercise : calculate and print the result of this operation


  $$\frac{15}{3+2}-(\frac{\frac{100}{4}}{5})*2$$
  
  

Numeric data et operations 2/2
========================================================


> - Differences between integers and floats


> - Arithmetic operators + - * / %


> - Exercise : calculate and print the result of this operation


$$\frac{15}{3+2}-(\frac{\frac{100}{4}}{5})*2$$

```{python echo=TRUE}
x = 15/(3+2) - (100/4/5)*2
print(x)
```


Strings 1/3
========================================================


> - Use to store text (most of the time)

> - Strings are declared with double quotation marks (" ") or single quotation marks (' '). Be careful when printing a string already stored in a variable. Examples:

```{python echo=TRUE}
animal = "Dog"
course = 'Intro to programming in python'

print(animal)
print("animal")

```


Strings 2/3
========================================================


> - String can easily be concatenated with the operator +


```{python echo=TRUE}
greetings = "Hello"
presentation = "My name is"
name = "Henri"
print( greetings + presentation + name)
```

> - Exercise: insert white space between the words.


Strings 2/3
========================================================


> - String can easily be concatenated with the operator +


```{python echo=TRUE}
greetings = "Hello"
presentation = "My name is"
name = "Henri"
print( greetings + presentation + name)
```

> - Exercise: insert white space between the words.
```{python echo=TRUE}
greetings = "Hello"
presentation = "My name is"
name = "Henri"
print( greetings + ' ' + presentation + ' ' + name)

space = ' '
print(greetings + space + presentation + space + name)
```


Strings 3/3
========================================================

- Functions working with strings:

  - **len()** calculate the length of a function. Example:
    ```{python echo=TRUE}
    greetings = "Hello"
    print(len(greetings))
    ```    
    
  - **replace()** can replace a pattern in a string. Example:
    ```{python echo=TRUE}
    greetings = "Hello"
    print(greetings)
    print(greetings.replace('e','a'))
    ```  
    
  - ...
  
  
Booleans
========================================================    
    
  - A boolean is a relatively simple variable but can sometimes be challenging to work with.
  
  - It can have only two values **True** or **False**
  
  - It is used usually to store the truth value of logic. Example:
    ```{python echo=TRUE}
    Is_it_Weekend = False
    print(Is_it_Weekend)
    ```


Program flow 1/4
========================================================

- A program typically executes sequentially, moving from top to bottom.

- But some instructions can change the flow. For examples *if* and *for* loops 

- **if** will test a conditional comparison. If the condition is true, we can execute certain lines of code; if it's false, those lines of code may not be executed (though other code may still be executed). Example 1:

    ```{python echo=TRUE}
    Weekend = False
    if Weekend == True :
      print("Let's do nothing and chill")
    else:
      print("Time to go to work")
    ```


Program flow 1/4
========================================================

- A program typically executes sequentially, moving from top to bottom.

- But some instructions can change the flow. For examples *if* and *for* loops 

- **if** will test a conditional comparison. If the condition is true, we can execute certain lines of code; if it's false, those lines of code may not be executed (though other code may still be executed). Example2 :
  ```{python echo=TRUE}
  string = "This string is long but not that long"

  if len(string) < 10:
    print("This string has less than 10 character")
  elif len(string) < 20:
    print("This string has less than 20 character")
  elif len(string) >30:
    print("That string is too long for me...")
  ```

Program flow 2/4
========================================================

- You can also define other alternatives with **elif**

- you can make use different ways to make your comparison:
      - **and** 
      - **or**
      - **not**
  
- You can as well use comparative expressions:
      - **<** 
      - **>**
      - **<=**
      - **==** tests for equality
      - **!=** tests for inequality

- Be careful **=** is not the same as **==**
  ```{python echo=TRUE, error=TRUE}
  age = 30 #(affectation)

  age == 30 #(equality comparison that returns TRUE if correct)
  
  age == 31
  ```      

Program flow 3/4
========================================================

- **for** loops iterate one or a set of operations multiple times.

Example 1:

```{python echo=TRUE}
for x in range(5):
  print(x)
```    

Program flow 3/4
========================================================

- **for** loops iterate one or a set of operations multiple times.

Example 1:

```{python echo=TRUE}
for x in range(5):
  print(x)
```

Example 2:

```{python echo=TRUE}
for i in range(5,10):
  print(i)
```    

Program flow 4/4
========================================================

- With **for** loops, you can observe that your program flow is not always unidirectional from the top to the bottom of your script.

- Let's play a small game. Download

  https://github.com/chrplr/PCBS/blob/master/games/human-guess-a-number.py


- Then go on http://pythontutor.com/ and paste the code of the game.

- Examine the program flow to observe how it transitions from one code section to another.


Clarification on for loops
========================================================
  - A **for** loop is used to iterate over the elements of a sequence (such as a string, tuple, set, list, or dictionary) or another iterable object.:
  
  - It differs from other **for** keyword in other programming languages and works more like an iterator.
  ```{python, echo=TRUE}
  list1 = [1,2,3,0]
  for x in list1:
    print(x)
  ```
  - It is almost similar to (which is much closer to the "traditional" for loop in programming)
  ```{python, echo=TRUE}
  list2 = [1,2,3,0]
  for x in range(0,len(list2)):
    print(list2[x])
  ```


Exercises
========================================================

> - Exercise 1: Write code that prints the string "All work and no play makes Jack a dull boy" 50 times

> - Exercise 2: Write code that prints the squares of all integers between 1 and 100 using the *range* function.

> - Exercise 3: Write code that iterates through integers from 0 to 100 but only prints the numbers 1, 50, and 100.

> - Exercise 4: Write code that prints only even numbers between 0 and 100

> - Exercise 5: Write code that computes the factorial of an integer using a loop (without using a function or recursion).