---
title: "intro to programming 5"
author: "Henri Vandendriessche"
date: "12/10/2021"
fontsize: 8pt
output:
  slidy_presentation: default
  beamer_presentation: default

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
So far
========================================================

  - Python, its life, its choice

  - Data types: (integer / float / string / boolean)
  
  - **If**, **For** and **While** loops: 

  - Data collections: (list, tuple, set, dictionary)
    
  - Functions
  
  - Higher order function (Recursive function)


Today
========================================================


### - Read and write files

### - Building abstraction with high order functions (part 1)

### - clean code


Manipulate files : Open and read a file
========================================================

- To do so you have one function available in the built-in functions of python
  + https://docs.python.org/3/library/functions.html

- The function **open()**
  + that works like that 
       open(file, mode='r', buffering=- 1, encoding=None, errors=None, newline=None, closefd=True, opener=None)
       
- see https://docs.python.org/3/library/functions.html#open
      
- Mode can be:
  + "r" - Read - Default value. Opens a file for reading, error if the file does not exist
  + "a" - Append - Opens a file for appending, creates the file if it does not exist
  + "w" - Write - Opens a file for writing, creates the file if it does not exist
  + "x" - Create - Creates the specified file, returns an error if the file exist


```{python, echo = TRUE}
Myfile = open('Survival rules for programming.txt', 'r')
print(Myfile.read())
Myfile.close()

Myfile = open('Survival rules for programming.txt', 'r')
print(Myfile.read(5))

print(Myfile.readlines(1))
print(Myfile.readlines()[1])
```


Manipulate files : create a file
========================================================

- Note that if you don't specify any path, it will be created in the current directory (ie, same directory as your script). It's called creating a file using a **relative path**

```{python, echo = TRUE}
import os
path = os.getcwd()

print(os.listdir(path))

MyTestFile = open('test.txt', 'x')

print(os.listdir(path))
```
- If you want to create in a precise directory you can specify it using an **absolute path**
```{python, echo = TRUE, eval = FALSE}
MyTestFile = open('/home/henri/Desktop/test.txt', 'x')
```


Manipulate files : write a file
========================================================
   
   - We need an access mode 'w' if we want to create and write anything into a file
   
   - Note that to be able to read a just created file you need to close it and open it again in read mode
```{python, echo = TRUE}
MyTestFile = open('test2.txt', 'w')

MyTestFile.write("Once upon a time in a Cognitive Master")

MyTestFile.close()

MyTestFile = open('test2.txt', 'r')

print(MyTestFile.read())
```


Manipulate files : append text to a file
========================================================

```{python, echo = TRUE}
MyTestFile = open('test2.txt', 'a')

MyTestFile.write("There was a module names Intro to programming")

MyTestFile.close()

MyTestFile = open('test2.txt', 'r')

print(MyTestFile.read())
```


Manipulate files : specific character and new lines
========================================================

- Inside a string you can use the antislash to insert special codes:
  + **\n** return to line
  + **\t** add a tab
  + **\r** return to line (same as \n in python)
  + **\"** add a quotation mark inside a string delimited itself by **"**

```{python, echo = TRUE}
MyTestFile = open('test2.txt', 'a')

MyTestFile.write("\nWith youngs and bright \tstudents \r!!!!!")

MyTestFile.close()

MyTestFile = open('test2.txt', 'r')

print(MyTestFile.read())
MyTestFile.close()
```


Manipulate files : Automatic close of the file
========================================================

- the **with open()** statement automatically close the file

```{python, echo = TRUE}
lines = ['and one last line', '\n... and one last...']

with open("test2.txt", "a") as MyTestFile:
    for line in lines: 
      MyTestFile.write(line)
```

```{python, echo = TRUE}
MyTestFile = open("test2.txt", "r")
print(MyTestFile.read())
```


Exercices
========================================================

  - 1 Write a script that prints the first 10 lines of a file
  - 2 Write a script that prints the last 10 lines of a file (or the whole file is it is less than 10 lines long)
  - 3 Write a script that opens and read a text file, and print all the lines that contain a given target word
  - 4 compute the number of the number of words (removing punctuation) in a text file
  - 5 compute the number of occurences of each word in a text file
  - 6 read a matrix in a text file and return the mean of each row (not using pandas, ...)
  - 7 find and list all *.csv files in a folder and its subfolders.
  - 8 rename all files in a folder by adding the last modification date and the end of the name (before the extension)


Exercices 1
========================================================

- 1 Write a script that prints the first 10 lines of a file

```{python, echo = TRUE}
MyTestFile = open('Survival rules for programming.txt', 'r')
lines = MyTestFile.readlines()

for i in range(10):
  print(lines[i])
```
```{python, echo = TRUE}
MyTestFile = open('Survival rules for programming.txt', 'r')
lines = MyTestFile.readlines()
print(lines[0:9])
```

Exercices 2
========================================================

- 2 Write a script that prints the last 10 lines of a file (or the whole file is it is less than 10 lines long)

```{python, echo = TRUE}
MyTestFile = open('Survival rules for programming.txt', 'r')
lines = MyTestFile.readlines()

for i in range(1,10):
  print(lines[-i])
```
Exercices 3
========================================================

- 3 Write a script that opens and read a text file, and print all the lines that contain a given target word

```{python, echo = TRUE}
```

Exercices 4
========================================================

- 4 compute the number of the number of words (removing punctuation) in a text file

```{python, echo = TRUE}
```

Exercices 5
========================================================

- 5 compute the number of occurences of each word in a text file

```{python, echo = TRUE}
```


Exercices 6
========================================================

- 6 read a matrix in a text file and return the mean of each row (not using pandas, ...)

```{python, echo = TRUE}
```


Exercices 7
========================================================

- 7 find and list all *.csv files in a folder and its subfolders.

```{python, echo = TRUE}
```

Exercices 8
========================================================

- 8 rename all files in a folder by adding the last modification date and the end of the name (before the extension)

```{python, echo = TRUE}
```

Exercices 5
========================================================

- 5 compute the number of occurences of each word in a text file

```{python, echo = TRUE}
```
number of lines
number of words
store number of words in dictionary

Plot it

Special character ?

Create a file

Read a csv file


"
    Querying and navigating the file system https://automatetheboringstuff.com/2e/chapter10/
    Reading and writing text files.
    Manipulating strings (split, join, ...). (chapter 10 of Swinnen's Apprendre à programmer avec Python 3)



create a log file of your script
Create File with a DateTime
Create a file with Permission

reading and writing files
file:///home/henri/Documents/Cours/Info-2/EXERCICES-2/python-exercices-02-doc.html#reading-and-writing-files

https://inforef.be/swi/download/apprendre_python3_5.pdf
